#env_name: !!str Pendulum-v0
env_name: !!str EmptyRoom22
device: !!str cpu                           # torch device (cuda:0 or cpu)
render_env: !!bool False                    # render environment

agents:
  gtn:
    mode: !!str 'multi'                     # 'single': run on single PC / 'multi': run on multiple PCs
    max_iterations: !!int 50                # maximum number of GTN iterations
    num_threads_per_worker: !!int 1         # how many pytorch/OMP threads per worker
    num_workers: !!int 16                   # size of the population
    num_test_envs: !!int -1                 # number of different test environments (-1: genereate default test env)
    noise_std: !!float 1e-1                 # standard deviation of the noise vector
    step_size: !!float 1                    # reptile step size
    nes_step_size: !!bool False             # when set to true, divide step size by the number of workers
    mirrored_sampling: !!bool True          # use normal or mirrored sampling
    num_grad_evals: !!int 1                 # how often to evaluate each gradient
    grad_eval_type: !!str mean              # mean or min
    weight_decay: !!float 0.0               # weight decay
    time_mult: !!float 3                    # maximum allocated time as multiplicative of avg. time
    time_max: !!float 100                   # maximum allocated time for first iteration
    time_sleep_master: !!float 0.2          # cycle sleeping time when waiting for data
    time_sleep_worker: !!float 2            # cycle sleeping time when waiting for data
    score_transform_type: !!int 7           # 0-7
    quit_when_solved: !!bool True           # continue training once the environment has been solved?
    synthetic_env_type: !!int 0             # 0: virtual env / 1: reward env
    unsolved_weight: !!float 10000          # penalty weight for all solvable environments if they haven't been solved yet
    agent_name: !!str QL                    # which RL agent to use for meta-training

  ddqn_vary:
    vary_hp: !!bool True                    # vary hyperparameters of underlying DDQN algorithm?

  reptile:
    max_iterations: !!int 20                # maximum number of REPTILE iteration
    step_size: !!float 0.1                  # step size when updating the model parameters
    agent_name: !!str TD3                   # which RL agent to use for meta-training
    parallel_update: !!bool True            # serial or parallel reptile updates?
    env_num: !!int 5                        # number of different training envs

  env_matcher:
    lr: !!float 1e-3                        # learning rate
    weight_decay: !!float 0                 # weight decay
    batch_size: !!int 128                   # batch size during training
    early_out_diff: !!float 0               # break criterion for matching
    early_out_num: !!int 100                # based on how many training steps shall an early out happen
    max_steps: !!int 2000                   # number of steps
    step_size: !!int 200                    # LR scheduler step size
    gamma: !!float 0.7                      # LR scheduler gamma
    match_loss_state: !!str L1              # "L1" or "L2"
    match_loss_reward: !!str L2             # "L1" or "L2"
    match_loss_done: !!str L1               # "L1" or "L2"

  ddqn:
    train_episodes: !!int 1000              # maximum number of episodes to train
    test_episodes: !!int 100                # maximum number of episodes to test
    init_episodes: !!int 10                 # number of episodes to fill the replay buffer
    batch_size: !!int 128                   # batch size when running a policy update step
    gamma: !!float 0.98                     # discount factor
    lr: !!float 3e-4                        # learning rate
    tau: !!float 0.01                       # target network update rate
    eps_init: !!float 0.1                   # initial random action percentage
    eps_min: !!float 0.01                   # final random action percentage
    eps_decay: !!float 0.8                  # random action decay factor
    rb_size: !!int 1000000                  # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    activation_fn: !!str relu               # activation function for actor/critic ('tanh', 'relu', 'leakyrelu' or 'prelu')
    hidden_size: !!int 64                   # size of the actor/critic hidden layer
    hidden_layer: !!int 1                   # number of hidden layers
    print_rate: 10000                       # update rate of avg meters
    early_out_episode: 1                    # check every i-th episode if an early out should happen
    early_out_num: 5                        # based on how many training steps shall an early out happen
    early_out_virtual_diff: !!float 1e-2    # performance difference for an early out for virtual envs

  ql:
    train_episodes: !!int 100               # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to optimize
    init_episodes: !!int 5                  # number of episodes to prevent an early out
    batch_size: !!int 4                     # batch size when running a policy update step
    alpha: !!float 0.5                      # Q-Learning update factor
    gamma: !!float 0.9                      # discount factor
    eps_init: !!float 0.5                   # initial random action percentage
    eps_min: !!float 0.01                   # final random action percentage
    eps_decay: !!float 0.95                 # random action decay factor
    rb_size: !!int 100000                   # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    print_rate: 1000                        # update rate of avg meters
    early_out_episode: 1                    # check every i-th episode if an early out should happen
    early_out_num: 10                       # based on how many training steps shall an early out happen
    early_out_virtual_diff: !!float 1e-2    # performance difference for an early out for virtual envs

  sarsa:
    train_episodes: !!int 1000               # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to optimize
    init_episodes: !!int 5                  # number of episodes to prevent an early out
    batch_size: !!int 4                     # batch size when running a policy update step
    alpha: !!float 0.5                      # Q-Learning update factor
    gamma: !!float 0.9                      # discount factor
    eps_init: !!float 0.5                   # initial random action percentage
    eps_min: !!float 0.01                   # final random action percentage
    eps_decay: !!float 0.95                 # random action decay factor
    rb_size: !!int 100000                   # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    print_rate: 1000                        # update rate of avg meters
    early_out_episode: 1                    # check every i-th episode if an early out should happen
    early_out_num: 10                       # based on how many training steps shall an early out happen
    early_out_virtual_diff: !!float 1e-2    # performance difference for an early out for virtual envs

  td3:
    train_episodes: !!int 50                # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to optimize
    init_episodes: !!int 20                 # number of episodes to fill the replay buffer
    batch_size: !!int  256                  # batch size when running a policy update step
    gamma: !!float 0.99                     # discount factor
    lr: !!float 1e-3                        # learning rate
    tau: !!float 0.02                       # target network update rate
    policy_delay: !!int 1                   # frequency of delayed policy updates
    rb_size: !!int 1000000                  # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    activation_fn: !!str relu               # activation function for actor/critic ('tanh', 'relu', 'leakyrelu' or 'prelu')
    hidden_size: !!int 256                  # size of the actor/critic hidden layer
    hidden_layer: !!int 2                   # number of hidden layers
    action_std: !!float 0.1                 # action noise standard deviation
    policy_std: !!float 0.2                 # policy noise standard deviation
    policy_std_clip: !!float 0.5            # policy noise standard deviation
    print_rate: 1                           # update rate of avg meters
    early_out_episode: 1                    # check every i-th episode if an early out should happen
    early_out_num: !!int 5                  # based on how many training steps shall an early out happen
    early_out_virtual_diff: !!float 1e-1    # performance difference for an early out for virtual envs

  ppo:
    train_episodes: !!int 10000             # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to optimize
    init_episodes: !!int 0                  # number of episodes to fill the replay buffer
    update_episodes: !!float 20             # update policy every x episodes (can be float)
    ppo_epochs: !!int 100                   # update policy for x epochs
    gamma: !!float 0.99                     # discount factor
    lr: !!float 5e-4                        # learning rate
    vf_coef: !!float 0.5                    # value function coefficient (see PPO paper)
    ent_coef: !!float 0.01                  # entropy coefficient (see PPO paper)
    eps_clip: !!float 0.2                   # trust region size (see PPO paper)
    rb_size: !!int 1000000                  # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    activation_fn: !!str relu               # activation function for actor/critic ('tanh', 'relu', 'leakyrelu' or 'prelu')
    hidden_size: !!int 128                  # size of the actor/critic hidden layer
    hidden_layer: !!int 1                   # number of hidden layers
    action_std: !!float 0.5                 # action noise standard deviation
    print_rate: 10                          # update rate of avg meters
    early_out_episode: 20                   # check every i-th episode if an early out should happen
    early_out_num: !!int 50                 # based on how many training steps shall an early out happen
    early_out_virtual_diff: !!float 1e-1    # performance difference for an early out for virtual envs

envs:
  Pendulum-v0:
    solved_reward: !!float -300             # used for early out in RL agent training
    max_steps: !!int 200                    # maximum number of steps per episode
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 2                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  MountainCarContinuous-v0:
    solved_reward: !!float 80               # used for early out in RL agent training
    max_steps: !!int 999                    # maximum number of steps per episode REMOVE
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 96                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 2                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  HalfCheetah-v2:
    solved_reward: !!float 3000             # used for early out in RL agent training
    max_steps: !!int 1000                   # maximum number of steps per episode
    activation_fn: !!str relu               # activation function of the virtual environment
    hidden_size: 128                        # size of the hidden layer of the virtual environment
    hidden_layer: !!int 3                   # number of hidden layers of the virtual environment
    info_dim: !!int 2                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  HalfCheetah-v3:
    solved_reward: !!float 300              # used for early out in RL agent training
    max_steps: !!int 1000                   # maximum number of steps per episode
    activation_fn: !!str relu               # activation function of the virtual environment
    hidden_size: 128                        # size of the hidden layer of the virtual environment
    hidden_layer: !!int 3                   # number of hidden layers of the virtual environment
    info_dim: !!int 4                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  CartPole-v0:
    solved_reward: !!float 195              # used for early out in RL agent training
    max_steps: !!int 200                    # maximum number of steps per episode
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 128                        # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  LunarLander-v2:
    solved_reward: !!float 200
    max_steps: !!int 1000
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 128                        # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  FrozenLake-v0:
    solved_reward: !!float 0.9
    max_steps: !!int 50
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 16                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  CliffWalking-v0:
    solved_reward: !!float -50
    max_steps: !!int 100
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 16                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  Bandit:
    solved_reward: !!float 49
    max_steps: !!int 50
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 4                          # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  EmptyRoom22:
    solved_reward: !!float 0.8
    max_steps: !!int 10
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  EmptyRoom23:
    solved_reward: !!float 0.8
    max_steps: !!int 15
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  EmptyRoom33:
    solved_reward: !!float 0.8
    max_steps: !!int 20
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  WallRoom:
    solved_reward: !!float 0.8
    max_steps: !!int 50
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function

  HoleRoom:
    solved_reward: !!float 0.8
    max_steps: !!int 50
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 32                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function
