env_name: !!str HalfCheetah-v3
device: !!str cpu                           # torch device (cuda:0 or cpu)
render_env: !!bool False                    # render environment

agents:
  td3:
    train_episodes: !!int 100               # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to evaluate
    init_episodes: !!int 20                 # number of episodes to fill the replay buffer
    batch_size: !!int  255                  # batch size when running a policy update step
    gamma: !!float 0.972                    # discount factor
    lr: !!float 0.00345                     # learning rate
    tau: !!float 0.0486                     # target network update rate
    policy_delay: !!int 2                   # frequency of delayed policy updates
    rb_size: !!int 1000000                  # size of the replay buffer
    same_action_num: !!int 1                # how often to perform the same action subsequently
    activation_fn: !!str leakyrelu          # activation function for actor/critic ('tanh', 'relu', 'leakyrelu' or 'prelu')
    hidden_size: !!int 67                   # size of the actor/critic hidden layer
    hidden_layer: !!int 2                   # number of hidden layers
    action_std: !!float 0.0525              # action noise standard deviation
    policy_std: !!float 0.141               # policy noise standard deviation
    policy_std_clip: !!float 0.540          # policy noise standard deviation
    print_rate: 5                           # update rate of avg meters
    early_out_num: !!int 5                  # based on how many training episodes shall an early out happen
    early_out_virtual_diff: !!float 0.0892  # performance difference for an early out for virtual envs

envs:
  HalfCheetah-v3:
    solved_reward: !!float 3000             # used for early out in RL agent training
    max_steps: !!int 1000                   # maximum number of steps per episode
    activation_fn: !!str relu               # activation function of the virtual environment
    hidden_size: 171                        # size of the hidden layer of the virtual environment
    hidden_layer: !!int 1                   # number of hidden layers of the virtual environment
    info_dim: !!int 4                       # additional information dimension from step function
    reward_env_type: !!int 2                # type of reward shaping function

