env_name: !!str MountainCarContinuous-v0
device: !!str cuda                          # torch device (cuda:0 or cpu)
render_env: !!bool False                     # render environment

agents:
  td3:
    train_episodes: !!int 100               # maximum number of episodes to optimize
    test_episodes: !!int 10                 # maximum number of episodes to optimize
    init_episodes: !!int 50                 # number of episodes to fill the replay buffer
    batch_size: !!int  210                  # batch size when running a policy update step
    gamma: !!float 0.985                    # discount factor
    lr: !!float 0.00310                     # learning rate
    tau: !!float 0.0478                     # target network update rate
    policy_delay: !!int 1                   # frequency of delayed policy updates
    rb_size: !!int 1000000                  # size of the replay buffer
    same_action_num: !!int 2                # how often to perform the same action subsequently
    activation_fn: !!str prelu              # activation function for actor/critic ('tanh', 'relu', 'leakyrelu' or 'prelu')
    hidden_size: !!int 58                   # size of the actor/critic hidden layer
    hidden_layer: !!int 2                   # number of hidden layers
    action_std: !!float 0.0709              # action noise standard deviation
    policy_std: !!float 0.263               # policy noise standard deviation
    policy_std_clip: !!float 0.320          # policy noise standard deviation
    print_rate: 1                           # update rate of avg meters
    early_out_num: !!int 5                  # based on how many training episodes shall an early out happen
    early_out_virtual_diff: !!float 0.0180  # performance difference for an early out for virtual envs

envs:
  MountainCarContinuous-v0:
    solved_reward: !!float 90               # used for early out in RL agent training
    max_steps: !!int 999                    # maximum number of steps per episode REMOVE
    activation_fn: !!str leakyrelu          # activation function of the virtual environment
    hidden_size: 96                         # size of the hidden layer of the virtual environment
    hidden_layer: !!int 2                   # number of hidden layers of the virtual environment
    info_dim: !!int 0                       # additional information dimension from step function
    reward_env_type: !!int 0                # type of reward shaping function
